# Generated by Django 3.2.3 on 2021-05-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('dob', models.DateField(null=True)),
                ('website', models.URLField(null=True)),
                ('profile_url', models.URLField(max_length=500, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=2)),
            ],
            options={
                'ordering': ['name', 'phone_no', 'gender'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter genre for movie eg: Action, comedy etc', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(help_text='Enter subtitles for movie ex: english,hindi etc', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('movie_url', models.URLField(max_length=500, null=True)),
                ('img_url', models.URLField(max_length=500)),
                ('asin', models.CharField(help_text='Enter Amazon Standard Identification Number', max_length=20, unique=True)),
                ('directors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.director')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this movie', to='movie.Genre')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.studio')),
            ],
        ),
    ]
